image:
  file: .gitpod.Dockerfile

tasks:
  # Install dependencies first.
  - init: pip install -r ./requirements.txt
    # Then run if there's config.env, otherwise prompt to configure.
    command: >
      if [[ -f config.env ]]; then
        bash run
      else
        echo "Please edit the config.env.sample and rename it to 'config.env'. Then to run do-> bash run"
      fi
