# Quotes for AutoBio 

# English Quotes 
ENGLISH_QUOTES = [

    "Best way to earn respect is By treating others with respect ",
    "Win in silence. Let them think you're losing. ",
    "The biggest slap to your enemies is your success.‌‌ ",
    "Winners never quit and Quitters Never win. ",
    "And if you love, love their darkness too, not just their light. ",
    "Sometimes losing people makes you find yourself. ",
    "Belive in yourself. You will survive whatever is coming. ",
    "is here any sweet is being sold here, you came to see. ",
    "Do something today that your future self will thank you for. ",
    "Don't forget God when you get what you've prayed for. ",
    "Be happy with what you have, while working for what you want. ",
    "You can only win when your mind is stronger than your emotions. ",
    "Keep your dreams big and your worries small. ",
    "If someone makes you happy, make them happier. ",
    "Tag a friend who has been with you in your hard times. ",
    "Winning isn't everything, but wanting to win is. ",
    "If you interested to read bio's, then why not take bio. ",
    "A champion is someone who gets up when he can't. ",
    "If you can believe it, the mind can achieve it. ",
    "Game doesn't build character, it reveals character! ",
    "If you train hard, you'll not only be hard, you'll be hard to beat. ",
    "You win some, lose some, and wreck some. ",
    "Age is no barrier. It's a limitation you put on your mind. ",
    "Nobody roots for Goliath. ",
    "Set your goals high, and don't stop till you get there. ",
    "Statistics are like bikinis—they show a lot but not everything. ",
    "You miss 100 percent of the shots you don't take. ",
    "The way to get started is to quit talking and begin doing. ",
    "Your time is limited, so don't waste it living someone else's life. ",
    "That which does not kill us makes us stronger. "]


# Hindi Quotes 
HINDI_QUOTES = [

    "अपने दुश्मनों के लिए सबसे बड़ा थप्पड़ आपकी सफलता है।‌‌ ",
    "चुप्पी में जीत। उन्हें लगता है कि आप हार रहे हैं। ",
    "जीतने वाले कभी हार नही मानते और हार मानने वाले कभी जीतते नही‌‌ ",
    "कभी-कभी लोगों को खोने से आप खुद को पाते हैं। ",
    "अपने आप पर विश्वास करो। आप जो भी आ रहा है उससे बच जाएंगे। ",
    "यहाँ क्या कोई मिठाई बट रही है जो आप देखने आए।। ",
    "आज कुछ ऐसा करें कि आपका भविष्य स्वयं आपको धन्यवाद दे। ",
    "आप तभी जीत सकते हैं जब आपका दिमाग आपकी भावनाओं से अधिक मजबूत हो। ",
    "अपने सपनों को बड़ा रखो और अपनी चिंताओं को छोटा करो। ",
    "केवल तीन प्रकार के लोग सच्चाई बताते हैं: बच्चे, शराबी और क्रोधी। ",
    "अगर कोई आपको खुश करता है, तो उन्हें खुश करें। ",
    "एक मित्र को टैग करें जो आपके कठिन समय में आपके साथ रहा हो। ",
    "आजाद रहिये विचारों से..लेकिन बंधे रहिये अपने संस्कारों से..। ",
    "सपने को पाने के लिए समझदार नहीं पागल बनना पड़ता है ",
    "जीतने का मजा तब ही आता है,जब सभी आपके..हारने का इंतजार कर रहे हो! ",
    "जो खुद खुश रहते है उनसे दुनिया खुश रहती है। ",
    "सबसे छोटा कार्य सबसे महान इरादे से हमेशा बेहतर होता है ",
    "सत्य भी यदि अनुचित है तो उसे नहीं कहना चाहिए। ",
    "जो जिस कार्ये में कुशल हो उसे उसी कार्ये में लगना चाहिए। ",
    "दोषहीन कार्यों का होना दुर्लभ होता है। ",
    "किसी भी कार्य में पल भर का भी विलम्ब न करें। ",
    "अगर आपको बायो पढ़ने का शौक है, तो बायो क्यों नही ली।‌‌ ",
    "पहले निश्चय करिएँ, फिर कार्य आरम्भ करें। ",
    "भाग्य पुरुषार्थी के पीछे चलता है। ",
    "ज़िंदगी आगे बढ़ने  का नाम है, रुकने का नही..! ",
    "बादाम खाने से उतनी अक्ल नहीं आती, जितनी धोखा खाने से आती है। ",
    "प्यार से भागना आपको चोट से नहीं बचाता, वो दर असल प्यार पाने से रोकता है। ",
    "जो सबका मित्र  होता है, वो दरअसल  किसी का मित्र नहीं होता ",
    "वक्त पर अपनी  गलती ना मानना एक और गलती करना है। ",
    "किसी माथे को चूमना उसकी रूह को चूमना जैसा है। ",
    "शुक्रगुजार होना भी एक आदत है, इसकी आदत डालनी पड़ती है। "]